In [1]:
import keras

ModuleNotFoundError: No module named 'keras'

In [ ]:
a = 5

In [ ]:
b = a*4
b

## Arithmetic Operations

In [ ]:
r = 1500
t = 0.2


total = r * (1 + t)
total

In [ ]:
2!=3

and or not

In [ ]:
(10>5) and (10<5)

## List

In [2]:
l = [10,20,30,40]

In [ ]:
l = [10, 'test1234','mest', [40,10], 123, 8.4]

0-5

In [9]:
len(l)-2

4

In [6]:
l[len(l)-2]

123

In [6]:
len(l[1])

8

In [ ]:
len(l)

In [ ]:
l.append(50)

In [7]:
l = ['data1.csv', 'data2.csv', 'data3.csv']

## Tuple

In [8]:
t = (10, 12, 13)

```sql
INSERT INTO TABLE ... VALUES
(value1, value2)
```

## Set

In [11]:
my_list = [1, 2, 3, 4, 5,5,5,5,5]

In [14]:
my_set = set(my_list)
new_l = list(my_set)
new_l

[1, 2, 3, 4, 5]

In [9]:
a = {1,2,3,4,5}
b = {4,5,6,7,8}

In [10]:
a.intersection(b)

{4, 5}

## Dictionary

In [17]:
# key value pairs
customers = {
             'Alice': 25, 
             'Bob': 30, 
             'Charlie': 35,
             'Charlie': 31,
             'Charlie': [32,2]
             }

In [18]:
customers

{'Alice': 25, 'Bob': 30, 'Charlie': [32, 2]}

In [ ]:
customers['Alice'] = 30

In [ ]:
customers

In [19]:
customer = {'name': 'Alice', 'age': 30, 'city': 'New York'}
customer['State'] = 'NY'
customer['Segment'] = 'Premium'

In [20]:
customer1 = customer
customer1

{'name': 'Alice',
 'age': 30,
 'city': 'New York',
 'State': 'NY',
 'Segment': 'Premium'}

In [21]:
# Bob
customer2 = {'name': 'Bob', 'age': 25, 'city': 'Los Angeles', 'State': 'CA', 'Segment': 'Standard'}

In [22]:
# Armen
customer3 = {'name': 'Armen', 'age': 28, 'city': 'Chicago', 'State': 'IL'}

In [23]:
list_of_customers = [customer1, customer2, customer3]

In [24]:
list_of_customers

[{'name': 'Alice',
  'age': 30,
  'city': 'New York',
  'State': 'NY',
  'Segment': 'Premium'},
 {'name': 'Bob',
  'age': 25,
  'city': 'Los Angeles',
  'State': 'CA',
  'Segment': 'Standard'},
 {'name': 'Armen', 'age': 28, 'city': 'Chicago', 'State': 'IL'}]

In [20]:
list(list_of_customers[0].keys())

NameError: name 'list_of_customers' is not defined

In [26]:
l = [10,20,30,40]
d = {'key', 'value'}

## Pandas

In [25]:
import pandas as pd
import numpy as np

In [26]:
data = {'name': ['Alice', 'Bob', 'Charlie','David','Armen'], 
        'age': [30, 25, 28, 35, 42], 
        'city': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'San Francisco'],
        'revenue': [10000, 15000, 12000, 20000, 18000],
        'segment': ['Premium', 'Premium', 'Premium', 'Standard', 'Premium']}

In [34]:

list(data.values())

temp_list = [['v1','v2'],['c1','c2']]

In [ ]:
temp_list[1][0]

['c1', 'c2']

In [27]:
df = pd.DataFrame(data)
df.head()

      name  age           city  revenue   segment
0    Alice   30       New York    10000   Premium
1      Bob   25    Los Angeles    15000   Premium
2  Charlie   28        Chicago    12000   Premium
3    David   35         Boston    20000  Standard
4    Armen   42  San Francisco    18000   Premium

In [40]:
df.loc[df["revenue"] > 12000,"segment"] = "High Revenue"

In [41]:
df.head()

      name  age           city  revenue       segment
0    Alice   30       New York    10000       Premium
1      Bob   25    Los Angeles    15000  High Revenue
2  Charlie   28        Chicago    12000       Premium
3    David   35         Boston    20000  High Revenue
4    Armen   42  San Francisco    18000  High Revenue

## IF Statement

In [1]:
revenue = 101

if revenue > 100:
    print("High revenue")
    print(f"Because the revenue is: {revenue}")
    
else:
    print("Low Revenue")

print("Analysis complete")

High revenue
Because the revenue is: 101
Analysis complete

In [ ]:
revenue = 100

if revenue > 200:
    print(f"Very high revenue: {revenue}")
elif revenue > 100:
    print(f"High revenue: {revenue}")
elif revenue > 50:
    print(f"Medium revenue: {revenue}")
else:
    print(f"Low revenue: {revenue}")

Medium revenue: 100

```sql
CASE WHEN condition THEN value_if_true ELSE value_if_false END
```

In [ ]:
is_active = False


if is_active:
    print('Okay')
    # MY CODE / LOGIC

## Bolean

In [6]:
a != b

True

In [8]:
revenue = 90
is_active = False

if revenue > 100 or is_active:
    print("Target customer")

In [ ]:
is_active = False
if not is_active:
    print("Customer is active")

Customer is active

In [15]:
revenue = 100

if revenue == 100:
    print('Revenue is 100')
    if is_active:
        print('Great')
    else:
        print('Bad')
else:
    print('reveneu is not 100')

Revenue is 100
Bad

## Loops

In [ ]:
'(? ? ? ? ? ?)'

In [33]:
f"({df.shape[1]*'?, '})"

'(?, ?, ?, ?, ?, )'

In [19]:
5*'a'

'aaaaa'

In [44]:
sales = [10,20,30,40,50,84,0,212]

sales[0] = sales[0]*2
sales[1] = sales[1]*2
sales[2] = sales[2]*2
sales[3] = sales[3]*2
sales[4] = sales[4]*2

In [45]:
for i in range(2,10,2):
    print(i)

2
4
6
8

In [46]:
sales

[20, 40, 60, 80, 100, 84, 0, 212]

In [58]:
len(sales)

for i in range(8):
    print(i)

0
1
2
3
4
5
6
7

In [ ]:
for i in range(len(sales)):
    
    sales[i] = sales[i]*2

sales

[40, 80, 120, 160, 200, 168, 0, 424]

In [ ]:
sales

total = 0

for i in sales:
    print(f'Total before {total}')
    print(20*'-')
    total = total + i
    print(20*'-')
    print(f'Total after {total}' )

Total before 0
--------------------
--------------------
Total after 40
Total before 40
--------------------
--------------------
Total after 120
Total before 120
--------------------
--------------------
Total after 240
Total before 240
--------------------
--------------------
Total after 400
Total before 400
--------------------
--------------------
Total after 600
Total before 600
--------------------
--------------------
Total after 768
Total before 768
--------------------
--------------------
Total after 768
Total before 768
--------------------
--------------------
Total after 1192

In [55]:
sales
sales_new = []
total = 0

for i in sales:
    sales_new.append(i*2)

print(sales)
print(sales_new)

[40, 80, 120, 160, 200, 168, 0, 424]
[80, 160, 240, 320, 400, 336, 0, 848]

In [ ]:
loser = []
sales_new = []
for i in sales:
    sales_new.append(i*2)
    else:
        loser.append(i) 

print(loser)
print(sales_new)

[0]
[80, 160, 240, 320, 400, 336, 848]

In [68]:
customer = {
    "data_name1": "data_url1",
    "data_name2": "data_url2",
    "data_name3": "data_url3",
    "data_name4": "data_url4",
    
}

for key in customer.keys():
    print(f'Download `{customer[key]}` and `save in some folder` and name it as `{key}`.csv')

Download `data_url1` and `save in some folder` and name it as `data_name1`.csv
Download `data_url2` and `save in some folder` and name it as `data_name2`.csv
Download `data_url3` and `save in some folder` and name it as `data_name3`.csv
Download `data_url4` and `save in some folder` and name it as `data_name4`.csv

In [ ]:
for key, value in customer.items():
    print(f'Download `{value}` and `save in some folder` and name it as `{key}`.csv')

Download `data_url1` and `save in some folder` and name it as `data_name1`.csv
Download `data_url2` and `save in some folder` and name it as `data_name2`.csv
Download `data_url3` and `save in some folder` and name it as `data_name3`.csv
Download `data_url4` and `save in some folder` and name it as `data_name4`.csv

In [70]:
for i in range(3):
    for j in range(2):
        print("i =", i, ", j =", j)

i = 0 , j = 0
i = 0 , j = 1
i = 1 , j = 0
i = 1 , j = 1
i = 2 , j = 0
i = 2 , j = 1

## List Comprehentions

In [ ]:
sales

[40, 80, 120, 160, 200, 168, 0, 424]

In [72]:
new_sales = [i*2 for i in sales]
new_sales

[80, 160, 240, 320, 400, 336, 0, 848]

In [81]:
a = 'abcdefg'

a_l = [i for i in a]

a_l

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [84]:
l = [10,20,20,0]

l_1 = [i for i in l if i>0]
l_0 = [i for i in l if i==0]

l_0

[0]

In [ ]:
["Champion" if value>0 else "Loser" for value in l]

['Champion', 'Champion', 'Champion', 'Loser']

In [78]:
",".join(a_l)

'a,b,c,d,e,f,g'

In [75]:
c = a
a = b
b = c

In [77]:
a = a + b

In [79]:
b = a - b
a = a - b

In [84]:
print(f" a is equal to: {a}  \n b is equal to: {b}")

 a is equal to: 6
 b is equal to: 5

In [93]:
print(revenue)
if revenue == 150:
    print("Equal")

150
Equal

In [90]:
a = 5; b = 10; c = 15

In [94]:
if revenue > 100:
    print("High")

High

In [95]:
list_of_data_sources = ['data1.csv', 'data2.csv', 'data3.csv']

In [97]:
for i in list_of_data_sources:
    print(f'then name of current data source is: {i}')

print("Exit loop")

then name of current data source is: data1.csv
then name of current data source is: data2.csv
then name of current data source is: data3.csv
Exit loop

In [ ]:
number_of_clicks = 0

for i in range(100):
    number_of_clicks = i + 1

number_of_clicks

5

In [101]:
sales = [100, 200, 150, 50]

for value in sales:
    if value > 120:
        print("High sale:", value)
    else:
        print("Low sale:", value)

Low sale: 100
High sale: 200
High sale: 150
Low sale: 50

In [ ]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

In [107]:
customer.keys()
customer['name']

'Anna'

In [108]:
customer['city']

'Yerevan'

In [111]:
customer['revenue']

150

In [2]:
customer = {
    "name": ["Anna", "Gagik"],
    "revenue": [150, 200],
    "city": ["Yerevan"]
}

customer

{'name': ['Anna', 'Gagik'], 'revenue': [150, 200], 'city': ['Yerevan']}

In [3]:
customer.items()

dict_items([('name', ['Anna', 'Gagik']), ('revenue', [150, 200]), ('city', ['Yerevan'])])

In [6]:

for key, value in customer.items():
    print(key)
    print(key, ":", customer[key][1])

name
name : Gagik
revenue
revenue : 200
city

IndexError: list index out of range

In [10]:
l= [10,20,30,40,50]
for i in l[3:]:
    print(i)

40
50

In [11]:
l[:3]

[10, 20, 30]