In [2]:
## Unzipping File
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw/")

In [3]:
del zip_ref

In [ ]:
## Import packages
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

In [44]:
df_orders = pd.read_csv('../data/raw/orders.csv'
    #     usecols=['order_id', 'user_id', 'order_number', 'order_dow',
    #    'order_hour_of_day', 'days_since_prior_order'
    #    ]
       )

In [20]:
df_orders.head(n= 5)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In [12]:
df_orders.tail()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [17]:
print(f"""
the shape of the data: {df_orders.shape}
number of rows: {df_orders.shape[0]}
number of columns: {df_orders.shape[1]}
""")

the shape of the data: (3421083, 7)
number of rows: 3421083
number of columns: 7

In [ ]:
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [23]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [25]:
df_orders.rename(columns={'order_id': 'order_number','order_dow':'day_of_week'},
                 inplace= True)

# IT IS THE SAME AS df_orders = df_orders.rename(columns={'order_id': 'order_number','order_dow':'day_of_week'})

In [26]:
df_orders.head()

,order_number,user_id,eval_set,order_number,day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [27]:
type(df_orders.head())

pandas.DataFrame

In [28]:
shape = df_orders.shape
type(shape)

tuple

In [29]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_number            int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   day_of_week             int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 198.9 MB

In [30]:
if df_orders.shape[0] > 1000000:
    print('DANGER')
else:
    print('OKAY')

DANGER

In [28]:
shape

(3421083, 7)

In [29]:
print(type(df_orders.shape))
print(f" The # of rows: {df_orders.shape[0]} \n The # of columns: {df_orders.shape[1]}")

<class 'tuple'>
 The # of rows: 3421083
 The # of columns: 7

In [30]:
## List of column
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [31]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [32]:
df_orders.tail()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [35]:
df_orders.drop(columns= ['eval_set'], inplace=True)

In [36]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 6 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_number            int64
 1   user_id                 int64
 2   order_number            int64
 3   day_of_week             int64
 4   order_hour_of_day       int64
 5   days_since_prior_order  float64
dtypes: float64(1), int64(5)
memory usage: 156.6 MB

In [37]:
df_orders.dtypes

order_number                int64
user_id                     int64
order_number                int64
day_of_week                 int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [39]:
pd.options.display.float_format = '{:,.2f}'.format

In [ ]:
s

In [47]:
df_orders

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.00
3421079,1854736,206209,prior,11,4,10,30.00
3421080,626363,206209,prior,12,1,12,18.00
3421081,2977660,206209,prior,13,1,12,7.00
3421082,272231,206209,train,14,6,14,30.00

In [49]:
# summary statistics
df_orders.describe(exclude=['str'])

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [36]:
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [50]:
df_orders.drop(columns = ['eval_set'], inplace = True)

In [ ]:
df_orders.astype({'order_id': 'str'})

# df_orders.dtypes

TypeError: NDFrame.astype() got an unexpected keyword argument 'inplace'

In [63]:
df_orders['order_id_str'] = df_orders['order_id'].astype('str')

df_orders.head()
df_orders.dtypes

order_id                    int64
user_id                     int64
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
order_id_str                  str
dtype: object

In [58]:
df_orders.dtypes

order_id                    int64
user_id                     int64
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [64]:
df_orders.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,order_id_str
0,2539329,1,1,2,8,NaN,2539329
1,2398795,1,2,3,7,15.00,2398795
2,473747,1,3,3,12,21.00,473747
3,2254736,1,4,4,7,29.00,2254736
4,431534,1,5,4,15,28.00,431534

In [ ]:
df_orders['my_new_column'] = [int(i) for i in df_orders['order_hour_of_day']/3]
df_orders['my_new_column'] = df_orders['order_hour_of_day']//3
# df_orders['my_new_column'] = 'Testt'
df_orders.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,order_id_str,my_new_column
0,2539329,1,1,2,8,NaN,2539329,2
1,2398795,1,2,3,7,15.00,2398795,2
2,473747,1,3,3,12,21.00,473747,4
3,2254736,1,4,4,7,29.00,2254736,2
4,431534,1,5,4,15,28.00,431534,5

In [72]:
df_orders_new = df_orders.assign(
    is_weekend = df_orders["order_dow"].isin([0, 6]),
    is_morning = df_orders["order_hour_of_day"] < 12,
    # is_premium = df_orders["days_since_prior_order"] <= 7
)

In [73]:
df_orders_new.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,order_id_str,my_new_column,is_weekend,is_morning
0,2539329,1,1,2,8,NaN,2539329,2,False,True
1,2398795,1,2,3,7,15.00,2398795,2,False,True
2,473747,1,3,3,12,21.00,473747,4,False,False
3,2254736,1,4,4,7,29.00,2254736,2,False,True
4,431534,1,5,4,15,28.00,431534,5,False,False

In [ ]:
df_orders['order_dow'].value_counts()

order_dow
0    600905
1    587478
2    467260
5    453368
6    448761
3    436972
4    426339
Name: count, dtype: int64

In [75]:
df_orders['order_dow'].value_counts(normalize=True)

order_dow
0   0.18
1   0.17
2   0.14
5   0.13
6   0.13
3   0.13
4   0.12
Name: proportion, dtype: float64

In [92]:
v_counts = pd.DataFrame(df_orders['order_dow'].value_counts(normalize=True))

v_counts.reset_index(inplace=True)

In [93]:
v_counts

   order_dow  proportion
0          0        0.18
1          1        0.17
2          2        0.14
3          5        0.13
4          6        0.13
5          3        0.13
6          4        0.12

In [95]:
v_counts.sort_values(by='order_dow',ascending=False,inplace=True)
v_counts

   order_dow  proportion
4          6        0.13
3          5        0.13
6          4        0.12
5          3        0.13
2          2        0.14
1          1        0.17
0          0        0.18

In [97]:
v_counts.reset_index(drop=True,inplace=True)
v_counts

   order_dow  proportion
0          6        0.13
1          5        0.13
2          4        0.12
3          3        0.13
4          2        0.14
5          1        0.17
6          0        0.18

In [98]:
df_orders_new['days_since_prior_order'] = df_orders_new['days_since_prior_order'].fillna(0)

In [100]:
df_orders_new.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,order_id_str,my_new_column,is_weekend,is_morning
0,2539329,1,1,2,8,0.00,2539329,2,False,True
1,2398795,1,2,3,7,15.00,2398795,2,False,True
2,473747,1,3,3,12,21.00,473747,4,False,False
3,2254736,1,4,4,7,29.00,2254736,2,False,True
4,431534,1,5,4,15,28.00,431534,5,False,False

In [102]:
# 174MB with index and bolean column (0-N)
# 146MB առանց index
# 153MB ինդեքսով՝ առանց միհատ բուլիան սյունակի
df_orders_new.to_csv('../data/processed/order_new.csv',index=False)

In [103]:
df_products = pd.read_csv('../data/raw/products.csv')
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [50]:
df_products.drop(columns=['aisle_id'],inplace=True)

In [59]:
df_departments = pd.read_csv('../data/raw/departments.csv')

In [60]:
df_departments.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [64]:
df_temp_t = df_departments.T
df_temp_t.head()

                        0
department_id  department
1                  frozen
2                   other
3                  bakery
4                 produce

In [70]:
df_temp_t.info()

<class 'pandas.DataFrame'>
Index: 22 entries, department_id to 21
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       22 non-null     str
dtypes: str(1)
memory usage: 908.0+ bytes

In [71]:
df_products.reset_index()

,index,product_id,product_name,department_id,prices
0,0,1,Chocolate Sandwich Cookies,19,5.8
1,1,2,All-Seasons Salt,13,9.3
2,2,3,Robust Golden Unsweetened Oolong Tea,7,4.5
3,3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,1,10.5
4,4,5,Green Chile Anytime Sauce,13,4.3
...,...,...,...,...,...
49688,49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",5,5.3
49689,49689,49685,En Croute Roast Hazelnut Cranberry,1,3.1
49690,49690,49686,Artisan Baguette,3,7.8
49691,49691,49687,Smartblend Healthy Metabolism Dry Cat Food,8,4.7
49692,49692,49688,Fresh Foaming Cleanser,11,13.5

In [73]:
df_temp_t.reset_index(inplace=True)

In [80]:
df_temp_t.head()

           index           0
0  department_id  department
1              1      frozen
2              2       other
3              3      bakery
4              4     produce

In [90]:

col_names = df_temp_t.iloc[0]
col_names

index    department_id
0           department
Name: 0, dtype: str

In [91]:
department_main_data = df_temp_t.iloc[1:]
department_main_data.head()

  index        0
1     1   frozen
2     2    other
3     3   bakery
4     4  produce
5     5  alcohol

In [92]:
department_main_data.columns = col_names

In [89]:
department_main_data.head()

  Excel      SQL
1     1   frozen
2     2    other
3     3   bakery
4     4  produce
5     5  alcohol

In [95]:
department_main_data.reset_index(inplace=True)

In [96]:
department_main_data.head()

0  index department_id department
0      1             1     frozen
1      2             2      other
2      3             3     bakery
3      4             4    produce
4      5             5    alcohol

In [104]:
df_departments = pd.read_csv("../data/raw/departments.csv")
df_departments.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [ ]:
df_t = df_departments.T

In [114]:
df_t.reset_index(inplace=True)

In [117]:
df_t

            index                0
0   department_id       department
1               1           frozen
2               2            other
3               3           bakery
4               4          produce
5               5          alcohol
6               6    international
7               7        beverages
8               8             pets
9               9  dry goods pasta
10             10             bulk
11             11    personal care
12             12     meat seafood
13             13           pantry
14             14        breakfast
15             15     canned goods
16             16       dairy eggs
17             17        household
18             18           babies
19             19           snacks
20             20             deli
21             21          missing

In [116]:
df_t.iloc[0]

index    department_id
0           department
Name: 0, dtype: str

In [128]:
myl = [1,2,2,3,5]
myl[2:4]

myl[:4]

[1, 2, 2, 3]

In [129]:
df_t.columns = df_t.iloc[0]
df_t = df_t.iloc[1:]

In [132]:
df_t.reset_index(drop=True,inplace=True)

In [133]:
df_t

0  department_id       department
0              1           frozen
1              2            other
2              3           bakery
3              4          produce
4              5          alcohol
5              6    international
6              7        beverages
7              8             pets
8              9  dry goods pasta
9             10             bulk
10            11    personal care
11            12     meat seafood
12            13           pantry
13            14        breakfast
14            15     canned goods
15            16       dairy eggs
16            17        household
17            18           babies
18            19           snacks
19            20             deli
20            21          missing

In [1]:
# Get current working directory
import os
print("Current working directory:", os.getcwd())

Current working directory: /Users/karen/Desktop/aca/lab/python/notebooks

In [ ]:
../data/raw/customers.csv