## Installing Packages

In [1]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

## Importing Data

In [2]:
# Reading data
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [5]:
df_orders.tail()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
3421078,2266710,206209,prior,10,5,18,29.00
3421079,1854736,206209,prior,11,4,10,30.00
3421080,626363,206209,prior,12,1,12,18.00
3421081,2977660,206209,prior,13,1,12,7.00
3421082,272231,206209,train,14,6,14,30.00

In [3]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [4]:
df_products = pd.read_csv('../data/raw/products.csv')
print(df_products.columns)
print(df_products.shape)
df_products.head()

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices'], dtype='str')
(49693, 5)

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [5]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', 'department'], dtype='str')
(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [6]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

## Working with `Orders`

In [7]:

df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [8]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [9]:
df_orders['order_id'].nunique()

3421083

In [10]:
df_orders.shape

(3421083, 7)

In [11]:
## Consistancy Check: Order ID
if df_orders['order_id'].nunique() == df_orders.shape[0]:
    print('Happy')
else:
    print('Sad')

Happy

In [12]:
## 
df_orders['order_id'].nunique() == df_orders.shape[0]

True

In [13]:
df_orders['user_id'].nunique()

206209

In [14]:
df_orders['order_id'].nunique()/df_orders['user_id'].nunique()

16.590367054784224

In [15]:
df_orders['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [16]:
df_dow = df_orders['order_dow'].value_counts(ascending=False).reset_index().sort_values('order_dow')

In [17]:
df_dow.to_csv('../data/processed/dow.csv', index=False)

In [18]:
df_ohod = df_orders['order_hour_of_day'].value_counts().reset_index().sort_values('order_hour_of_day')
df_ohod.head()

    order_hour_of_day  count
18                  0  22758
19                  1  12398
21                  2   7539
23                  3   5474
22                  4   5527

In [19]:
df_ohod.to_csv('../data/processed/ohod.csv')

In [20]:
df_ohod.to_excel('../data/processed/ohod.xlsx',index=False)

In [21]:
df_orders["order_number"] == 1

0           True
1          False
2          False
3          False
4          False
           ...
3421078    False
3421079    False
3421080    False
3421081    False
3421082    False
Name: order_number, Length: 3421083, dtype: bool

In [22]:
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

In [32]:
needed_columns = ['days_since_prior_order','order_number','user_id']

In [29]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [34]:
df_first_orders = df_orders[['days_since_prior_order','order_number','user_id']]

In [35]:
df_first_orders.head()

   days_since_prior_order  order_number  user_id
0                     NaN             1        1
1                   15.00             2        1
2                   21.00             3        1
3                   29.00             4        1
4                   28.00             5        1

In [36]:
df_orders["order_id"].nunique()

3421083

In [37]:
df_orders["order_dow"].between(0, 6).all()

np.True_

In [38]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [39]:
df_orders_train.shape

(131209, 7)

In [44]:
df_orders_products_train["reordered"].value_counts(normalize=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [45]:
df_orders_products_train["reordered"].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

In [46]:
df_orders_products_train["add_to_cart_order"].describe()

count   1,384,617.00
mean            8.76
std             7.42
min             1.00
25%             3.00
50%             7.00
75%            12.00
max            80.00
Name: add_to_cart_order, dtype: float64

In [ ]:
atr = 8/10

0.8

In [53]:
df_orders_products_train["order_id"].is_unique

False

In [63]:
df_orders_products_train.head(10)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1
5         1       13176                  6          0
6         1       47209                  7          0
7         1       22035                  8          1
8        36       39612                  1          0
9        36       19660                  2          1

In [56]:
df_orders_products_train["order_id"].is_unique

False

In [65]:
# add to cart order is one
df_orders_first_atc = df_orders_products_train[df_orders_products_train["add_to_cart_order"]==1]
df_orders_first_atc.shape

(131209, 4)

In [74]:
df_orders_first_atc.head()

    order_id  product_id  add_to_cart_order  reordered
0          1       49302                  1          1
8         36       39612                  1          0
16        38       11913                  1          0
25        96       20574                  1          1
32        98        8859                  1          1

In [ ]:
# 24852 
df_orders_first_atc['product_id'].value_counts()

product_id
24852    4605
13176    3889
27845    1144
47766     995
21137     900
         ...
7044        1
28344       1
40866       1
13539       1
40800       1
Name: count, Length: 17908, dtype: int64

In [67]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [71]:
df_products.shape

(49693, 5)

In [72]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  str
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 3.4 MB

In [73]:
df_products.describe()

       product_id  aisle_id  department_id    prices
count   49,693.00 49,693.00      49,693.00 49,693.00
mean    24,844.35     67.77          11.73      9.99
std     14,343.72     38.32           5.85    453.52
min          1.00      1.00           1.00      1.00
25%     12,423.00     35.00           7.00      4.10
50%     24,845.00     69.00          13.00      7.10
75%     37,265.00    100.00          17.00     11.20
max     49,688.00    134.00          21.00 99,999.00

In [88]:
df_products[df_products['product_name'].isna()==True]

       product_id product_name  aisle_id  department_id  prices
33             34          NaN       121             14   12.20
68             69          NaN        26              7   11.80
115           116          NaN        93              3   10.80
261           262          NaN       110             13   12.10
525           525          NaN       109             11    1.20
1511         1511          NaN        84             16   14.30
1780         1780          NaN       126             11   12.30
2240         2240          NaN        52              1   14.20
2586         2586          NaN       104             13   12.40
3159         3159          NaN       126             11   13.10
3230         3230          NaN       120             16   14.40
3736         3736          NaN        41              8   14.80
4283         4283          NaN        77              7   14.40
4790         4790          NaN        91             16   14.50
38187       38183          NaN        39             12   20.90
40444       40440          NaN       120             16   14.80

In [86]:
49688-49693

-5

In [77]:
# 13176
df_products[df_products['product_id']==24852]

       product_id product_name  aisle_id  department_id  prices
24853       24852       Banana        24              4   12.30

In [83]:
df_products.sort_values(by='prices', ascending = False).head(1)

       product_id           product_name  aisle_id  department_id    prices
33666       33664  2 % Reduced Fat  Milk        84             16 99,999.00

In [89]:
df_products["product_id"].nunique()

49686

In [90]:
df_products.shape

(49693, 5)

In [92]:
df_departments.head()
df_departments.shape

(21, 2)

In [93]:
df_departments

    department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli
20             21          missing

In [94]:
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [96]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [116]:
df_products_aisles =  pd.merge(df_products, df_aisles, on= "aisle_id", how = "left")

In [117]:
df_products_aisles.head()

,product_id,product_name,aisle_id,department_id,prices,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation

In [118]:
df_products_aisles.head()

,product_id,product_name,aisle_id,department_id,prices,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation

In [ ]:
df_products_aisles_department = pd.merge(df_products_aisles,df_departments, 
                                         on = 'department_id',
                                         how = 'left'
                                         
                                        )

In [120]:
df_products_aisles_department.head()

,product_id,product_name,aisle_id,department_id,prices,aisle,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes,snacks
1,2,All-Seasons Salt,104,13,9.30,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation,pantry

In [126]:
df_products_aisles_department.drop(columns = ['aisle_id', 'department_id'], inplace = True)

In [124]:
del df_departments
del df_products
del df_aisles

In [127]:
df_products_aisles_department.head()

,product_id,product_name,prices,aisle,department
0,1,Chocolate Sandwich Cookies,5.80,cookies cakes,snacks
1,2,All-Seasons Salt,9.30,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,4.50,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,10.50,frozen meals,frozen
4,5,Green Chile Anytime Sauce,4.30,marinades meat preparation,pantry

In [128]:
df_products_aisles_department['department'].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64