## Loading Packages

In [12]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

## Importing Dataframes

In [ ]:
df_orders = pd.read_csv('../data/raw/orders.csv')
print(df_orders.shape)
df_orders.head()

(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [14]:
df_orders.head

<bound method NDFrame.head of          order_id  user_id eval_set  order_number  order_dow  \
0         2539329        1    prior             1          2
1         2398795        1    prior             2          3
2          473747        1    prior             3          3
3         2254736        1    prior             4          4
4          431534        1    prior             5          4
...           ...      ...      ...           ...        ...
3421078   2266710   206209    prior            10          5
3421079   1854736   206209    prior            11          4
3421080    626363   206209    prior            12          1
3421081   2977660   206209    prior            13          1
3421082    272231   206209    train            14          6

         order_hour_of_day  days_since_prior_order
0                        8                     NaN
1                        7                   15.00
2                       12                   21.00
3                        7                   29.00
4                       15                   28.00
...                    ...                     ...
3421078                 18                   29.00
3421079                 10                   30.00
3421080                 12                   18.00
3421081                 12                    7.00
3421082                 14                   30.00

[3421083 rows x 7 columns]>

In [3]:
df_orders['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [9]:
df_orders_train = df_orders[df_orders['eval_set'] == 'train']
print(df_orders_train.shape)
df_orders_train.head()

df_orders_train.to_csv('../data/processed/orders_train.csv',index=False)

(131209, 7)

In [10]:
del df_orders

In [17]:
df_products = pd.read_csv('../data/raw/products.csv')
print(df_products.shape)
df_products.head()

(49693, 5)

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [13]:
df_customers = pd.read_csv('../data/raw/customers.csv')
print(df_customers.shape)
df_customers.head()

(206209, 10)

,user_id,First Name,Surname,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [15]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.shape)
df_departments.head()

(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [18]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.shape)
df_aisles.head()

(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [20]:
df_states = pd.read_csv('../data/raw/states.csv')
print(df_states.shape)
df_states.head()

(51, 3)

           state     region     division
0    Connecticut  Northeast  New England
1          Maine  Northeast  New England
2  Massachusetts  Northeast  New England
3  New Hampshire  Northeast  New England
4   Rhode Island  Northeast  New England

In [117]:
df_order_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_order_products_train.shape)
df_order_products_train.head()

(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

## Explore

### Orders

In [25]:
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [26]:
df_orders_train.info()

<class 'pandas.DataFrame'>
Index: 131209 entries, 10 to 3421082
Data columns (total 7 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                131209 non-null  int64
 1   user_id                 131209 non-null  int64
 2   eval_set                131209 non-null  str
 3   order_number            131209 non-null  int64
 4   order_dow               131209 non-null  int64
 5   order_hour_of_day       131209 non-null  int64
 6   days_since_prior_order  131209 non-null  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 8.6 MB

In [28]:
columns_to_explore =['order_dow','order_hour_of_day','days_since_prior_order']

df_orders_train[columns_to_explore].describe()

       order_dow  order_hour_of_day  days_since_prior_order
count 131,209.00         131,209.00              131,209.00
mean        2.77              13.58                   17.05
std         2.12               4.22                   10.68
min         0.00               0.00                    0.00
25%         1.00              10.00                    7.00
50%         3.00              14.00                   15.00
75%         5.00              17.00                   30.00
max         6.00              23.00                   30.00

In [31]:
df_orders_train.isna().sum()

order_id                  0
user_id                   0
eval_set                  0
order_number              0
order_dow                 0
order_hour_of_day         0
days_since_prior_order    0
dtype: int64

In [ ]:
df_orders_train['order_id'].nunique()

131209

In [34]:
df_orders_train['user_id'].nunique()

131209

In [38]:
df_orders['order_id'].nunique()

3421083

In [39]:
df_orders['user_id'].nunique()

206209

In [41]:
df_orders['eval_set'].value_counts(normalize=True)

eval_set
prior   0.94
train   0.04
test    0.02
Name: proportion, dtype: float64

In [42]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [44]:
df_orders['order_dow'].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

In [45]:
df_orders['order_hour_of_day'].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [49]:
df_orders['order_hour_of_day'].between(0,23).all()

np.True_

In [52]:
df_orders['order_dow'].between(0,6).all()

np.True_

In [ ]:
high_sales = [value for value in sales if value > 120]

In [ ]:
ValueError: Length of values (2232700) does not match length of index (3421083)

In [ ]:
"High" if value > 120 else "Low"

['Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Weekend',
 'Workday',
 'Workday',
 'Workday',
 'Weekend',
 'Weekend',
 'Workday',
 'Weekend',
 ...]

In [70]:
df_orders['weekend'] = ['Weekend' if i in  [0,6] else 'Workday' for i in df_orders['order_dow']]
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,weekend
0,2539329,1,prior,1,2,8,NaN,Workday
1,2398795,1,prior,2,3,7,15.00,Workday
2,473747,1,prior,3,3,12,21.00,Workday
3,2254736,1,prior,4,4,7,29.00,Workday
4,431534,1,prior,5,4,15,28.00,Workday

In [72]:
df_orders['weekend'].value_counts(normalize=True)

weekend
Workday   0.69
Weekend   0.31
Name: proportion, dtype: float64

### Customers

In [73]:
df_customers.head()

,user_id,First Name,Surname,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [77]:
df_customers['Gender'].value_counts(normalize=True)

Gender
Male     0.50
Female   0.50
Name: proportion, dtype: float64

In [83]:
df_customers[['n_dependants','fam_status']].value_counts(normalize=True)

n_dependants  fam_status
3             married                            0.23
1             married                            0.23
2             married                            0.23
0             single                             0.16
              divorced/widowed                   0.09
2             living with parents and siblings   0.02
1             living with parents and siblings   0.02
3             living with parents and siblings   0.02
Name: proportion, dtype: float64

In [91]:
df_customers[['Age','income']].describe().drop(['count'])

       Age     income
mean 49.50  94,632.85
std  18.48  42,473.79
min  18.00  25,903.00
25%  33.00  59,874.00
50%  49.00  93,547.00
75%  66.00 124,244.00
max  81.00 593,901.00

### Products_Train

In [120]:
df_order_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [126]:
df_order_products_train.shape

(1384617, 4)

In [ ]:
df_products[df_products['product_id']==24852]

       product_id product_name  aisle_id  department_id  prices
24853       24852       Banana        24              4   12.30

In [121]:
df_order_products_train[['product_id','add_to_cart_order']].value_counts()

product_id  add_to_cart_order
24852       1                    4605
13176       1                    3889
24852       2                    3199
13176       2                    2867
24852       3                    2255
                                 ...
7615        28                      1
40800       1                       1
33424       3                       1
16475       4                       1
6858        5                       1
Name: count, Length: 316364, dtype: int64

In [128]:

basket_size = len(df_order_products_train)/df_order_products_train['order_id'].nunique()

print('Averager Market Basket: ', basket_size)

Averager Market Basket:  10.552759338155157

In [129]:
df_order_products_train['product_id'].nunique()

39123

In [132]:
df_order_products_train['reordered'].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

### Products

In [135]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [137]:
df_products['product_id'].nunique()

49686

In [141]:
df_products['aisle_id'].nunique()

134

In [142]:
df_products['prices'].describe()

count   49,693.00
mean         9.99
std        453.52
min          1.00
25%          4.10
50%          7.10
75%         11.20
max     99,999.00
Name: prices, dtype: float64

In [143]:
df_departments

    department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli
20             21          missing

## Merge

`new_df = pd.merge(left_df,right_df, on = 'id', how  = 'left')`

In [147]:
df_products.head()
df_departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [ ]:
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left",
    indicator = True
)

df_products_departments.head(20)

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks,both
1,2,All-Seasons Salt,104,13,9.30,pantry,both
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages,both
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,both
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry,both

In [152]:
df_products_departments.dtypes

product_id          int64
product_name          str
aisle_id            int64
department_id       int64
prices            float64
department            str
_merge           category
dtype: object

In [153]:
df_products_departments['_merge'].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [ ]:

URL = 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/'

In [15]:

URL = 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/'
l = ['customers','states']

for i in l:
    dfname = URL + i +'.csv'
    df = pd.read_csv(dfname)
    df.to_csv(f'../data/raw/{i}_1.csv')
    print(dfname)

https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/customers.csv
https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/states.csv

In [ ]:
import pandas as pd
SQL_URL = "https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/"
TO_SAVE_URL = '/Users/karen/Desktop/aca/lab/sql_module/data/public_schema/'
l = ['customers', 'employees','orders','products', 'sales']

for i in l:
    print(100*'-')
    print(f"trying to download {i}.csv")
    print(SQL_URL+i+'.csv')
    # df = pd.read_csv(SQL_URL+i+'.csv')
    print(f"{i}.csv is downloaded")
    print(f"the shape of {i}.csv : {df.shape}")
    print(f"trying to save  {i}.csv")
    # df.to_csv(TO_SAVE_URL+i+'.csv',index=False)
    print(f"{i}.csv is successfully saved")

----------------------------------------------------------------------------------------------------
trying to download customers.csv
https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/customers.csv
customers.csv is downloaded
the shape of customers.csv : (5000, 8)
trying to save  customers.csv
customers.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download employees.csv
https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/employees.csv
employees.csv is downloaded
the shape of employees.csv : (5000, 8)
trying to save  employees.csv
employees.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download orders.csv
https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/orders.csv
orders.csv is downloaded
the shape of orders.csv : (5000, 8)
trying to save  orders.csv
orders.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download products.csv
https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/products.csv
products.csv is downloaded
the shape of products.csv : (5000, 8)
trying to save  products.csv
products.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download sales.csv
https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/sales.csv
sales.csv is downloaded
the shape of sales.csv : (5000, 8)
trying to save  sales.csv
sales.csv is successfully saved

In [ ]:
"/sfdsf/sdfdsfds/sdf"

In [ ]:
d

In [9]:
import pandas as pd
df = pd.read_csv(URL)
df
# df.to_csv('../data/raw/customers.csv', index=False)

                   state     region            division
0            Connecticut  Northeast         New England
1                  Maine  Northeast         New England
2          Massachusetts  Northeast         New England
3          New Hampshire  Northeast         New England
4           Rhode Island  Northeast         New England
5                Vermont  Northeast         New England
6             New Jersey  Northeast     Middle Atlantic
7               New York  Northeast     Middle Atlantic
8           Pennsylvania  Northeast     Middle Atlantic
9               Illinois    Midwest  East North Central
10               Indiana    Midwest  East North Central
11              Michigan    Midwest  East North Central
12                  Ohio    Midwest  East North Central
13             Wisconsin    Midwest  East North Central
14                  Iowa    Midwest  West North Central
15                Kansas    Midwest  West North Central
16             Minnesota    Midwest  West North Central
17              Missouri    Midwest  West North Central
18              Nebraska    Midwest  West North Central
19          North Dakota    Midwest  West North Central
20          South Dakota    Midwest  West North Central
21              Delaware      South      South Atlantic
22  District of Columbia      South      South Atlantic
23               Florida      South      South Atlantic
24               Georgia      South      South Atlantic
25              Maryland      South      South Atlantic
26        North Carolina      South      South Atlantic
27        South Carolina      South      South Atlantic
28              Virginia      South      South Atlantic
29         West Virginia      South      South Atlantic
30               Alabama      South  East South Central
31              Kentucky      South  East South Central
32           Mississippi      South  East South Central
33             Tennessee      South  East South Central
34              Arkansas      South  West South Central
35             Louisiana      South  West South Central
36              Oklahoma      South  West South Central
37                 Texas      South  West South Central
38               Arizona       West            Mountain
39              Colorado       West            Mountain
40                 Idaho       West            Mountain
41               Montana       West            Mountain
42                Nevada       West            Mountain
43            New Mexico       West            Mountain
44                  Utah       West            Mountain
45               Wyoming       West            Mountain
46                Alaska       West             Pacific
47            California       West             Pacific
48                Hawaii       West             Pacific
49                Oregon       West             Pacific
50            Washington       West             Pacific

## Parquet

1. Read Parquet file
2. Save to CSV
3. Compare the sizes


```bash
pip install pyarrow fastparquet
```

In [15]:
df_parquet = pd.read_parquet("../data/raw/order_products_prior.parquet")

In [16]:
df_parquet.shape

(32434489, 4)

In [18]:
df_parquet.info()

<class 'pandas.DataFrame'>
RangeIndex: 32434489 entries, 0 to 32434488
Data columns (total 4 columns):
 #   Column             Dtype
---  ------             -----
 0   order_id           int64
 1   product_id         int64
 2   add_to_cart_order  int64
 3   reordered          int64
dtypes: int64(4)
memory usage: 989.8 MB

In [17]:
df_parquet.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [19]:
df_parquet.to_csv('../data/raw/testsize.csv',index=False)