# Import Packages

In [3]:
import os
import pandas as pd
# Get current working directory
print("Current working directory:", os.getcwd())

Current working directory: /Users/karen/Desktop/aca/lab/python/notebooks

In [ ]:
dir_processed = os.path.join("../data","processed")
dir_raw = os.path.join("../data","processed")

In [8]:
data = pd.read_csv(os.path.join(dir_processed,"departments_t.csv"))
data

    department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli
20             21          missing

In [1]:
from pathlib import Path
import pandas as pd

### Declaring Path

In [2]:
raw_path = Path("../data/raw")
processed_path = Path("../data/processed")

### Loading the Data

In [3]:

df_orders = pd.read_csv(raw_path / "orders.csv")
df_orders_products_train = pd.read_csv(raw_path / "order_products_train.csv")
df_products = pd.read_csv(raw_path / "products.csv")
df_departments = pd.read_csv(processed_path / "departments_t.csv")
df_aisles = pd.read_csv(raw_path / "aisles.csv")

### Subset df_orders

We need only train rows

In [4]:
df_orders_train = (
    df_orders.loc[df_orders["eval_set"] == "train", [
        "order_id",
        "user_id",
        "order_number",
        "order_dow",
        "order_hour_of_day",
        "days_since_prior_order",
    ]]
    .copy()
)
df_orders_train.to_csv(processed_path / "orders_train.csv", index=False)
del df_orders


print(f'The Shape of the df_orders_train {df_orders_train.shape}')

df_orders_train

The Shape of the df_orders_train (131209, 6)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,11,4,8,14.0
25,1492625,2,15,1,11,30.0
49,2196797,5,5,0,11,6.0
74,525192,7,21,2,11,6.0
78,880375,8,4,1,14,10.0
...,...,...,...,...,...,...
3420838,2585586,206199,20,2,16,30.0
3420862,943915,206200,24,6,19,6.0
3420924,2371631,206203,6,4,19,30.0
3420933,1716008,206205,4,1,16,10.0
3421082,272231,206209,14,6,14,30.0

In [5]:

## products_departments
df_products_departments = df_products.merge(
    df_departments,
    on="department_id",
    how="left"
)

print(f'The Shape of the df_orders_train {df_products_departments.shape}')

The Shape of the df_orders_train (49693, 6)

In [6]:

df_products_departments.to_csv(
    processed_path / "products_departments.csv",
    index=False
)

In [7]:

del df_departments

### products_enriched

In [8]:


df_products_enriched = df_products_departments.merge(
    df_aisles,
    on="aisle_id",
    how="left"
)

In [9]:
df_products_enriched.to_csv(
    processed_path / "products_enriched.csv",
    index=False
)

In [10]:
del df_products_departments, df_aisles

# train_transactions

In [11]:



df_train_transactions = df_orders_train.merge(
    df_orders_products_train,
    on="order_id",
    how="left"
)
df_train_transactions.to_csv(
    processed_path / "train_transactions.csv",
    index=False
)
del df_orders_products_train

### final analytical table

In [13]:
### final analytical table
df_train_analytic = df_train_transactions.merge(
    df_products_enriched,
    on="product_id",
    how="left"
)
df_train_analytic.to_csv(
    processed_path / "train_analytic.csv",
    index=False
)

print("Final table shape:", df_train_analytic.shape)
df_train_analytic.head()

Final table shape: (1384706, 15)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,1187899,1,11,4,8,14.0,196,1,1,Soda,77.0,7.0,9.0,beverages,soft drinks
1,1187899,1,11,4,8,14.0,25133,2,1,Organic String Cheese,21.0,16.0,8.6,dairy eggs,packaged cheese
2,1187899,1,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,120.0,16.0,12.6,dairy eggs,yogurt
3,1187899,1,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,household,paper goods
4,1187899,1,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,45.0,19.0,6.8,snacks,candy chocolate

## Homework | Solution

In [14]:

data = ['customers.csv', 'states.csv']

URL = 'https://raw.githubusercontent.com/hovhannisyan91/aca/refs/heads/main/lab/python/data/raw/'

ldf = []
for i in data: 
    df = pd.read_csv(URL+i)
    # քանի որ ցանկանում ենք նաև միացնել տվյալները մենք կարող ենք դա անել միանգամից՝ նախ սկզբում պահելով այն լիստի մեջ
    ldf.append(df)

In [17]:
df_customers = ldf[0]
df_states = ldf[1]

In [18]:
df_states.head()

           state     region     division
0    Connecticut  Northeast  New England
1          Maine  Northeast  New England
2  Massachusetts  Northeast  New England
3  New Hampshire  Northeast  New England
4   Rhode Island  Northeast  New England

In [19]:
df_customers.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

## Attention

In [21]:
df_customers.rename(columns={'STATE':'state'}, inplace=True)

In [22]:
df_customers_states = df_customers.merge(df_states,on = 'state')

In [23]:
df_customers_states.head()

,user_id,First Name,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665,Midwest,West North Central
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285,West,Mountain
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568,West,Mountain
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049,Midwest,West North Central
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374,South,South Atlantic

In [29]:
df_train_analytics_final = df_train_analytic.merge(df_customers_states, on='user_id', how='left')
df_train_analytics_final.drop(columns='user_id',inplace=True)

In [ ]:
df_train_analytics_final.shape

(1384706, 26)

In [ ]:
df_train_analytics_final.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,1,11,4,8,14.0,196,1,1,Soda,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,1,11,4,8,14.0,25133,2,1,Organic String Cheese,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,1,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,1,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,1,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [ ]:
df_train_analytics_final.to_csv(processed_path / "final_table.csv",index= False)