## Dates

In [2]:
from datetime import datetime, date, timedelta

In [7]:
my_date = date(year=2025,month=3,day=24)

In [8]:
type(my_date)

datetime.date

In [12]:
my_time = datetime(year=2025,month=3,day=24, hour=14,minute=59,second=58)

In [13]:
my_time

datetime.datetime(2025, 3, 24, 14, 59, 58)

In [16]:
today = date.today()
today

datetime.date(2026, 3, 24)

In [17]:
now = datetime.now()
now

datetime.datetime(2026, 3, 24, 20, 1, 6, 143207)

In [25]:
my_date.strftime("%Y/%m/%d")

'2025/03/24'

In [26]:
my_date.strftime("%Y-%m-%d")

'2025-03-24'

In [31]:
my_date.strftime("%b %d %y")

'Mar 24 25'

In [33]:
my_date

datetime.date(2025, 3, 24)

In [43]:
start_date = my_date
end_date = datetime(2026,4,4)

In [37]:
delta = end_date -  start_date
delta

datetime.timedelta(days=376)

In [55]:

rd = (today + timedelta(days=5)).strftime("%b %d %y")
rd

'Mar 29 26'

## Dates with Pandas

In [58]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [60]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      str
 2   last_purchase  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 352.0 bytes

In [65]:
df_dates['signup_date'] = pd.to_datetime(df_dates['signup_date'])
df_dates['last_purchase'] = pd.to_datetime(df_dates['last_purchase'])

In [66]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

In [67]:
df_dates.to_csv('../data/test.csv', index=False)

In [ ]:
test = pd.read_csv('../data/test.csv',parse_dates=['signup_date',
                                                   'last_purchase'],
                                                   dtype={'customer_id':str})
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      str
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), str(1)
memory usage: 267.0 bytes

In [71]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

In [82]:
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day

In [85]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
 3   signup_year    5 non-null      int32
 4   signup_month   5 non-null      int32
 5   signup_day     5 non-null      int32
dtypes: datetime64[us](2), int32(3), int64(1)
memory usage: 312.0 bytes

In [95]:
df_dates["signup_month_name"] = df_dates["signup_date"].dt.month_name()
df_dates["signup_day_name"] = df_dates["signup_date"].dt.day_name()
df_dates["signup_dow"] = df_dates["signup_date"].dt.dayofweek

In [100]:
df_dates["is_weekend"] = (df_dates['signup_date'].dt.day_of_week>=5).astype(int)

In [107]:
df_dates['day_between_signup_purchase'] =  (df_dates['last_purchase'] - df_dates['signup_date']).dt.days

In [110]:
df_dates[df_dates['signup_date']>='2023-06-07']

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend,day_between_signup_purchase
0,101,2024-01-15,2024-06-01,2024,1,0,January,Monday,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,1,February,Tuesday,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,1,March,Tuesday,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,0,March,Monday,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,2,April,Wednesday,2,0,93

In [116]:
df_dates.sort_values('signup_date', ascending=False)

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend,day_between_signup_purchase
4,105,2024-04-10,2024-07-12,2024,4,2,April,Wednesday,2,0,93
3,104,2024-03-18,2024-07-08,2024,3,0,March,Monday,0,0,112
2,103,2024-03-05,2024-07-01,2024,3,1,March,Tuesday,1,0,118
1,102,2024-02-20,2024-06-15,2024,2,1,February,Tuesday,1,0,116
0,101,2024-01-15,2024-06-01,2024,1,0,January,Monday,0,0,138

In [117]:
df_dates.sort_values('signup_date')

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend,day_between_signup_purchase
0,101,2024-01-15,2024-06-01,2024,1,0,January,Monday,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,1,February,Tuesday,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,1,March,Tuesday,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,0,March,Monday,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,2,April,Wednesday,2,0,93

In [120]:
list(pd.date_range(start="2024-07-01", periods=7, freq="MS"))

[Timestamp('2024-07-01 00:00:00'),
 Timestamp('2024-08-01 00:00:00'),
 Timestamp('2024-09-01 00:00:00'),
 Timestamp('2024-10-01 00:00:00'),
 Timestamp('2024-11-01 00:00:00'),
 Timestamp('2024-12-01 00:00:00'),
 Timestamp('2025-01-01 00:00:00')]

In [121]:
import pandas as pd

some_date = pd.Timestamp("2024-07-15")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")

Original date: 2024-07-15 00:00:00
Beginning of month: 2024-07-01 00:00:00
End of month: 2024-07-31 23:59:59.999999

In [127]:
df_dates['bom'] = df_dates['signup_date'].dt.to_period('M').dt.start_time.dt.date
df_dates['eom'] = df_dates['signup_date'].dt.to_period('M').dt.end_time.dt.date

In [131]:
df_dates['signup_date'].dt.to_period('M').dt.start_time.dt.date

0    2024-01-01
1    2024-02-01
2    2024-03-01
3    2024-03-01
4    2024-04-01
Name: signup_date, dtype: object